name: Tailscale Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Test Tailscale API
        run: |
          echo "Testing Tailscale API..."
          
          curl -s \
          -u "${{ secrets.TAILSCALE_API }}:" \
          "https://api.tailscale.com/api/v2/tailnet/globesolution231.gmail.com/devices" \
          > response.json

          echo "===== RESPONSE ====="
          cat response.json
          echo ""
          echo "===== END ====="
